### ISSUE TITLE
any chance you could make a similar script like this but it's universal?

### ISSUE THREAD

**Issue by MechaXYZ** [coatlessali/UltraNix#4]
people could supply their own dummy project files for mac or whatever

**Comment by coatlessali** [comment]
If you mean cross-platform? It should be already.

If you mean working with every Unity game, then sadly no. This script only works because of a bunch of coincidences:

- ULTRAKILL supports OpenGL
- ULTRAKILL does not rely on any plugins that aren't available on Linux
- ULTRAKILL does not crash when a video can't be loaded
- ULTRAKILL uses mono instead of il2cpp.

Basically, it's a miracle this works at all.
